# Generated by Django 4.0.4 on 2022-10-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productt',
            new_name='Product',
        ),
    ]
